file_format: "1"
id: dactyl_manuform
name: Dactyl Manuform 5x7
type: shield
url: https://github.com/abstracthat/dactyl-manuform
requires: [pro_micro]
features:
  - keys
siblings:
  - dactyl_manuform_left
  - dactyl_manuform_right
